### PR TITLE
WIP Added a simple clang format file run on an example

### PR DESCRIPTION
**Pull request by jknedlik**
Like talked about in #6

### CODE REVIEW

**Comment by agarcia-gmf** [comment]
I don't mind much any (reasonable) code style, but if starting with an existing code base like in this case, i would prefer to find a style which "roughly" keeps the existing code untouched.

In particular, i would vote against reformatting the whole code just for changing IndentWidth from 4 to 2! :-)

**Comment by rberlich** [comment]
I would agree with Ariel there. Can the google style be incrementally changed? There are some settings that are dear to my heart, like placement of curly braces for functions, classes, and having arguments or initializer lists line by line, ordered by colon and comma. Denis' code for me already shows some funny formatting in Clion (not his fault, but resulting from a lack of common standards), so it may be useful to decide on a common style quickly. See also the comment about the summary of coding styles in the Geneva manual, as found in the Github "issues" section.

**Comment by agarcia-gmf** [comment]
@rberlich Yes, @jknedlik 's suggestion does just that:
```
BasedOnStyle: Google
IndentWidth: 2
ColumnLimit: 100
```
It starts with the full Google style, and modifies the indentation.
You can also skip the "BasedOnStyle" line and just list all the parameters you want to have.

**Comment by jknedlik** [comment]
> I don't mind much any (reasonable) code style, but if starting with an existing code base like in this case, i would prefer to find a style which "roughly" keeps the existing code untouched.
> 
> In particular, i would vote against reformatting the whole code just for changing IndentWidth from 4 to 2! :-)

@rberlich @agarcia-gmf 
I guess I am just too old fashioned? I just like to have nice readability on limited width, so I can work on a lot of files in parallel... It would be just one final merge commit anyway ;)
I am also not set on the Google style base, it was just as a starting point. Do you have any styles you would prefer?

I think I already found some additional formating options you might like

these would simply some of the easier conditions:
```
AllowShortIfStatementsOnASingleLine: true
AllowShortFunctionsOnASingleLine: true
AllowShortLoopsOnASingleLine: true
AlwaysBreakTemplateDeclarations: true
```
these might get @rberlich something that he wants for parameters:
```
BinPackArguments: false
BinPackParameters: false
ExperimentalAutoDetectBinPacking: false
AllowAllParametersOfDeclarationOnNextLine: false
```
This is what I like for braces
```
BreakBeforeBraces : Stroustrup
```
I will defend a low amount of indentwidth :P

**Comment by agarcia-gmf** [comment]
> I just like to have nice readability on limited width, so I can work on a lot of files in parallel...

having more than 5-6 levels of indentation decreases maintainability IMHO... that makes for 24 spaces indentation out of approx. 100 chars line width, and only 12 spaces "lost" with respect to your 2-indent proposal. Not that bad a tradeoff. I personally find 2 less readable than 4.

But reformatting the whole code also implies that "git annotate" immediately becomes less useful to look back into the history of changes...

Displays are able to hold much more than 80 cols and multiple windows side by side nowadays anyways.

**Comment by jknedlik** [comment]
> But reformatting the whole code also implies that "git annotate" immediately becomes less useful to look back into the history of changes...

Otherwise you will lose consice commits on all files edited in the future(which might become a hurdle to review) and then let blame become less useful then anyway. There is some Mitigation in forcing the first edit of a file commit to adhere to the old coding style, but then automatic formatting with clang-format would be broken...
(*I forgot about annotate even existing, used blame ever since*)

> having more than 5-6 levels of indentation decreases maintainability IMHO... that makes for 24 spaces indentation out of approx. 100 chars line width, and only 12 spaces "lost" with respect to your 2-indent proposal. Not that bad a tradeoff. I personally find 2 less readable than 4.
> Wide Displays are able to hold much more than 80 cols and multiple windows side by side nowadays anyways.

From my point, I'd rather not let my eyes jump between left and right a lot.
(And I already moved my hard 80 line rule because I know things like 

```cpp
std::shared_ptr<GStarterIndividual> bestIndividual_ptr = go.optimize()->getBestGlobalIndividual<GStarterIndividual>();
```
 exists within some nested scopes)

While a lot can be displayed on wide displays, I'd rather 
- work with my browser and a couple of source files where I can see a lot of code vertically.
- work on code in any environment
- especially working on your laptop while on the move / staying somewhere else
- have nicely sized code for slides
- comfortably merge files while editing things on the side
- following advices like [Typography and readability](https://www.semanticscholar.org/paper/Markus-Itkonen-Typography-and-readability-Itkonen-groteski/4b67cd16136d47682f547619e705e2151d2b98df) which even suggest 55-60 characters for printed text. (+ spacing for syntax bells and whistles = 80)
- not exclude people who don't have more than 1080p
- max should be 120 for github width anyway


(I might argue, if we need more than 100 characters for a code expression regularly, there might be something wrong inherently anyway, but I will not go as far now anyway) 
If one wants to commit to a width of 100/120, 12 characters saved are already over 10% of saved screen space while not degrading readability all that much (or maybe even improve, depending on your preferences). 

But If you are really really firm, we can go for 100/4 or 120/4.

**Comment by jknedlik** [comment]
For the time being we should also really use
```
SortIncludes: false
```

**Comment by jknedlik** [comment]
If you look at the files changed, there already is a lot of reformatting in just that one file

**Comment by agarcia-gmf** [comment]
> For the time being we should also really use
> 
> ```
> SortIncludes: false
> ```

What may be used to sort includes in groups is something like:

```
IncludeBlocks: Regroup
IncludeCategories:
  - Regex:           '<[[:alnum:]._/]+>'
    Priority:        1
  - Regex:           '^"(logging|json)/'
    Priority:        2
  - Regex:           '"[[:alnum:]._/]+"'
    Priority:        3
  - Regex:           '.*'
    Priority:        4
```
That puts all includes with angle brackets first, then the quoted ones starting with logging or json, and at the end it sorts all the rest. You get the idea. It can be used to sort the std includes first, boost next, and Geneva ones last for instance.

**Comment by jknedlik** [comment]
> > For the time being we should also really use
> > ```
> > SortIncludes: false
> > ```
> 

> That puts all includes with angle brackets first, then the quoted ones starting with logging or json, and at the end it sorts all the rest. You get the idea. It can be used to sort the std includes first, boost next, and Geneva ones last for instance.

I am still unsure if this is a wise decision... Is everything in geneva/boost defined correclty general, so the order doesnt matter (macros/typedef/enums/constants/...) ?

If it is, we can use
```
SortIncludes: true
IncludeBlocks: Regroup
IncludeCategories:
  # Headers in <boost/> from specific external libraries.
  - Regex:           '<[(boost)].+>'
    Priority:        1 
  # Headers in <geneva/> from specific external libraries.
  - Regex:           '<[(geneva)].+>'
    Priority:        2
  # Headers in <> 
  - Regex:           '<[[:alnum"].]+>'
    Priority:        3
  # Headers in "" with extension.
  - Regex:           '"[[:alnum:].]+"'
    Priority:        5
  - Regex:           '.*'
    Priority:        4
```

then 
```cpp
#include <geneva/Go2.hpp>
#include "GStarterIndividual.hpp"
#include <iostream>

#include <boost/test.hpp>
#include <geneva/GPluggableOptimizationMonitors.hpp>
```
becomes
```cpp
#include <boost/test.hpp>

#include <geneva/GPluggableOptimizationMonitors.hpp>
#include <geneva/Go2.hpp>

#include <iostream>

#include "GStarterIndividual.hpp"
```

**Comment by jknedlik** [comment]
> I am still unsure if this is a wise decision... Is everything in geneva/boost defined correclty general, so the order doesnt matter (macros/typedef/enums/constants/...) ?

It seems like it is fine, after running 
```bash
for file in `git ls-tree HEAD --name-only -r |grep -iE '\.(cpp|cc|h|hpp)$'` ; do clang-format -i --style=file "${file}" ; done
```
I was still able to `make` the lib correctly.

> Denis' code for me already shows some funny formatting in Clion (not his fault, but resulting from a lack of common standards), so it may be useful to decide on a common style quickly.

@r.berlich You thought of using [this](https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html#config-files), correct?

**Comment by jknedlik** [comment]
In general just running this right now on the codebase would yield 312 files changed, 100217 insertions, 109994 deletions, trashing git blame ofc.
So, what is your approach in which we are going to handle this? 
1. Slowly advancing it, losing some part after another, not adhering to the code convention completly, losing consice PRs
2. Going for code format convention on the whole base and losing git blame/annotate for prior changes
3. Another way you know to achieve both

I would vote for 2, in the lack of 3.

I also would like to know the circumstances of the PR being accepted, i.e. just to know what has to be done/ how much the style has to adhere to your factual code conventions to be accepted.

There are *a lot* of clang-format vars that we could still tweak, but it would be very helpful to have an example you would want to achieve, so we can talk about what needs to be changed on a file by file base. (Any file of your choosing, of course)

**Comment by jknedlik** [comment]
Right now we are using :
```
BreakBeforeBraces: Attach
```
and
```
BraceWrapping:
  AfterCaseLabel:  false
  AfterClass:      false
  AfterControlStatement: Never
  AfterEnum:       false
  AfterFunction:   false
  AfterNamespace:  false
  AfterObjCDeclaration: false
  AfterStruct:     false
  AfterUnion:      false
  AfterExternBlock: false
  BeforeCatch:     false
  BeforeElse:      false
  BeforeLambdaBody: false
  BeforeWhile:     false
  IndentBraces:    false
  SplitEmptyFunction: true
  SplitEmptyRecord: true
  SplitEmptyNamespace: true
```
which we could set explicitly, just like 
```
AlwaysBreakTemplateDeclarations: true
FixNamespaceComments: true
```
I think they already adhere closely to what is inside the docs.

**Pull request closed without merging**
